keywords = {
    "data_type": ["num", "string", "bool"],
    "class": ["class"],
    "this": ["this"],
    "super": ["super"],
    "static": ["static"],
    "access_modifier": ["public", "sealed"],
    "new": ["new"],
    "interface": ["interface"],
    "implements": ["implements"],
    "try": ["try"],
    "catch": ["catch"],
    "finally": ["finally"],
    "constructor": ["constructor"],
    "extends": ["::"],
    "final": ["final"],
    "func": ["func"],
    "return": ["return"],
    "returns": ["returns"],
    "void": ["void"],
    "if": ["if"],
    "else": ["else"],
    "elif": ["elif"],
    "for": ["for"],
    "while": ["while"],
    "jump_statements": ["break", "continue", "pass"],
    "arr_decl--1D": ["[]"],
    "arr_decl--2D": ["[][]"],
}

operators = {
    "inc_dec": ["++", "--"],
    "plus_minus": ["+", "-"],
    "multiply_divide_mod": ["*", "/", "%"],
    "assignment": ["="],
    "compound_assignment": ["+=", "-=", "*=", "/="],
    "relational_operators": [">", "<", "==", ">=", "<=", "!="],
    "and_operator": ["&&"],
    "or_operator": ["||"],
    "not_operator": ["!"],
}

punctuators = [":", ",", "(", ")", "{", "}", "[", "]", ".", "\\"]
